### ISSUE TITLE
liveBackup missing from level-hyper

### ISSUE THREAD

**Issue by heapwolf** [heapwolf/levelweb#5]
[`this`](https://github.com/hij1nx/levelweb/blob/backup/index.js#L52) method is always missing even when i pass in a `level-hyper` instance. any ideas? /cc @rvagg @maxogden

**Comment by rvagg** [comment]
hm, `db.db.liveBackup()` perhaps? I don't think it's exposed up in to the levelup layer even in level-hyper, it's a leveldown-layer detail.

**Comment by heapwolf** [comment]
agh! I thought i checked that, sure enough it's there! :)
